services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_DISPLAY_ERRORS: 0
      PHP_FPM: static # PROD: static
      PHP_FPM_PM_MAX_CHILDREN: 10 # PROD: 30
#    command: sh -c ""
    volumes:
      - ../code:/var/www/code
      - ../files/data/files:/var/www/html/web/sites/default/files
    networks:
      - dokploy-network
#  nginx:
#    image: wodby/drupal-nginx:$NGINX_TAG
#    container_name: "${PROJECT_NAME}_nginx"
#    depends_on:
#      - php
#    environment:
#      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
#      NGINX_ERROR_LOG_LEVEL: debug
#      NGINX_BACKEND_HOST: php
#      NGINX_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - ../code:/var/www/html
#      - ../files/data/files:/var/www/html/web/sites/default/files
#    networks:
#      - dokploy-network
networks:
  dokploy-network:
    external: true
